### ISSUE TITLE
suggestion: make y axis satoshi / byte, not satoshis / kb.

### ISSUE THREAD

**Issue by tphyahoo** [bitcoinfees/bitcoin-feemodel#1]
at https://bitcoinfees.github.io/#1m

20 sat / byte 

reads better than

20k sat / kbyte

This is an important chart btw.  I think it's going to be seeing a lot of attention soon.

So thanks for making it.

**Comment by bitcoinfees** [comment]
Thanks for the suggestion. Bitcoin Core uses "per kbyte" for all their fee rate parameters, so we're just trying to keep to the standard.
